version: '3.7'

services:

  frontend:
    container_name: frontend
    # image: 'node:14.16.0'
    build: 
      context: ./expression
      dockerfile: Dockerfile.frontend
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start

  backend:
    container_name: backend
    # image: 'node'
    build: 
      context: ./expression-server
      dockerfile: Dockerfile.backend
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 8080:8080
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
  
  database:
    container_name: database
    image: 'mongo'
    # build: 
    #   context: ./expression-server
    #   dockerfile: Dockerfile.backend
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - 27017:27017
    stdin_open: true
    environment:
      MONGO_INITDB_ROOT_USERNAME: example
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: campsites
    # command: npm start